[package]
name = "agentactr-sdk"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
agentactr-core.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
toml.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
