use crate::command_catalog::{command_catalog, CommandCatalogEntry};
use crate::{render_generated_help, AgentactrHelpCli};
use clap::CommandFactory;
use std::fs;
use std::path::{Path, PathBuf};

pub(crate) fn cmd_docs(args: &mut [String]) -> Result<(), String> {
    match args.get(1).map(String::as_str) {
        Some("cli-markdown") => cmd_docs_cli_markdown(args),
        _ => Err("usage: agentactr docs cli-markdown [--output PATH]".to_string()),
    }
}

fn cmd_docs_cli_markdown(args: &[String]) -> Result<(), String> {
    let mut output_path = None;
    let mut index = 2;
    while index < args.len() {
        match args.get(index).map(String::as_str) {
            Some("--output") => {
                let value = args
                    .get(index + 1)
                    .ok_or("usage: agentactr docs cli-markdown [--output PATH]")?;
                output_path = Some(PathBuf::from(value));
                index += 2;
            }
            _ => return Err("usage: agentactr docs cli-markdown [--output PATH]".to_string()),
        }
    }

    let markdown = render_cli_markdown()?;
    if let Some(path) = output_path {
        write_cli_markdown_output(&path, &markdown)?;
    } else {
        print!("{markdown}");
    }
    Ok(())
}

pub(crate) fn write_cli_markdown_output(path: &Path, markdown: &str) -> Result<(), String> {
    if path.as_os_str().is_empty() {
        return Err("docs output path must not be empty".to_string());
    }
    if path.exists() {
        let metadata =
            fs::symlink_metadata(path).map_err(|e| format!("inspect {}: {e}", path.display()))?;
        if metadata.file_type().is_symlink() {
            return Err(format!(
                "docs output path must not be a symlink: {}",
                path.display()
            ));
        }
        if metadata.is_dir() {
            return Err(format!(
                "docs output path must not be a directory: {}",
                path.display()
            ));
        }
    }
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent)
            .map_err(|e| format!("create docs output directory {}: {e}", parent.display()))?;
    }
    fs::write(path, markdown).map_err(|e| format!("write {}: {e}", path.display()))
}

pub(crate) fn render_cli_markdown() -> Result<String, String> {
    let mut output = String::new();
    output.push_str("# agentactr CLI Reference\n\n");
    output.push_str("<!-- Generated by `agentactr docs cli-markdown`; do not edit command sections by hand. -->\n\n");
    output.push_str(
        "This reference is generated from the typed `clap` command tree and the bootstrap command catalog. ",
    );
    output.push_str(
        "The catalog supplies implementation status, side effects, required credentials, platform constraints, and SDK use-case ownership.\n\n",
    );
    output.push_str("## Commands\n\n");

    for (help_path, entries) in command_catalog_help_groups() {
        output.push_str(&format!(
            "### `{}`\n\n",
            markdown_help_heading_command(&help_path)
        ));
        output.push_str("| Catalog command | Status | Side effects | SDK owner | Required credentials | Platform constraints | Purpose |\n");
        output.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
        for entry in entries {
            output.push_str(&format!(
                "| `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | {} |\n",
                markdown_table_cell(&format!("agentactr {}", entry.command)),
                markdown_table_cell(entry.status),
                markdown_table_cell(entry.side_effects),
                markdown_table_cell(entry.sdk_use_case_owner),
                markdown_table_cell(&markdown_list_or_none(entry.required_credentials)),
                markdown_table_cell(&markdown_list_or_none(entry.platform_constraints)),
                markdown_table_cell(entry.purpose)
            ));
        }
        output.push('\n');

        let help = trim_help_trailing_whitespace(&render_generated_help(&help_path)?);
        output.push_str("#### Generated Help\n\n");
        output.push_str("```text\n");
        output.push_str(help.trim_end());
        output.push_str("\n```\n\n");
    }

    Ok(output)
}

fn command_catalog_help_groups() -> Vec<(Vec<String>, Vec<&'static CommandCatalogEntry>)> {
    let mut groups: Vec<(Vec<String>, Vec<&CommandCatalogEntry>)> = Vec::new();
    for entry in command_catalog() {
        let help_path = catalog_help_path(entry.command);
        if let Some((_, entries)) = groups.iter_mut().find(|(path, _)| path == &help_path) {
            entries.push(entry);
        } else {
            groups.push((help_path, vec![entry]));
        }
    }
    groups
}

fn markdown_help_heading_command(help_path: &[String]) -> String {
    if help_path.is_empty() {
        "agentactr".to_string()
    } else {
        format!("agentactr {}", help_path.join(" "))
    }
}

pub(crate) fn markdown_table_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn markdown_list_or_none(values: &[&str]) -> String {
    if values.is_empty() {
        "none".to_string()
    } else {
        values.join(",")
    }
}

fn trim_help_trailing_whitespace(help: &str) -> String {
    help.lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
}

fn catalog_help_path(command: &str) -> Vec<String> {
    let mut root = AgentactrHelpCli::command();
    let mut path = Vec::new();
    let mut current = &mut root;
    for token in command.split_whitespace() {
        let Some(next) = current.find_subcommand_mut(token) else {
            break;
        };
        path.push(token.to_string());
        current = next;
    }
    path
}
